name: Check helix relayer config

on:
  pull_request:
#    branches:
#      - main

env:
  HELIXBRIDGE_CLI_VERSION: sha-f7618fb

jobs:
  check:
    name: Check changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: _${{ github.base_ref }}_

      - name: Check regiser
        run: |
          docker run -i --rm \
          --name helixbridge \
          -v $PWD:/relayer \
          -e FORCE_COLOR=1 \
          -e SIGNER=${{ secrets.SIGNER }} \
          ghcr.io/helix-bridge/helixbridge-cli:${HELIXBRIDGE_CLI_VERSION} \
            register --verbose --datadir=/relayer --group=itering

      - name: Check configure
        run: |
          docker run -i --rm \
          --name helixbridge \
          -v $PWD:/relayer \
          -e FORCE_COLOR=1 \
          -e SIGNER=${{ secrets.SIGNER }} \
          ghcr.io/helix-bridge/helixbridge-cli:${HELIXBRIDGE_CLI_VERSION} \
            generate-configure --verbose --datadir=/relayer --group=itering

      - uses: int128/diff-action@v1
        with:
          base: _${{ github.base_ref }}_/outputs
          head: outputs

      - name: Build comment
        run: |
          COMMENT_FILE='comment-configurate.md';
          for f in $(ls outputs/configure/*.json); do
            echo "<details>" >> $COMMENT_FILE
              echo "<summary>${f}</summary>" >> $COMMENT_FILE
              echo '' >> $COMMENT_FILE
              echo '```json' >> $COMMENT_FILE
              cat $f >> $COMMENT_FILE
              echo '' >> $COMMENT_FILE
              echo '```' >> $COMMENT_FILE
            echo '</details>' >> $COMMENT_FILE
            echo '' >> $COMMENT_FILE
          done

      - name: Comment configurate
        uses: GrantBirki/comment@v2
        with:
          file: comment-configurate.md
