name: Check helix relayer config

on:
  pull_request:
#    branches:
#      - main

env:
  HELIXBRIDGE_CLI_VERSION: sha-04b8c06

jobs:
  check:
    name: Check changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: _${{ github.base_ref }}_

      - name: Check regiser
        run: |
          docker run -i --rm \
          --name helixbridge \
          -v $PWD:/relayer \
          -e FORCE_COLOR=1 \
          -e SIGNER=${{ secrets.SIGNER }} \
          ghcr.io/helix-bridge/helixbridge-cli:${HELIXBRIDGE_CLI_VERSION} \
            register --verbose --datadir=/relayer --group=itering

      - name: Check configure
        run: |
          docker run -i --rm \
          --name helixbridge \
          -v $PWD:/relayer \
          -e FORCE_COLOR=1 \
          -e SIGNER=${{ secrets.SIGNER }} \
          ghcr.io/helix-bridge/helixbridge-cli:${HELIXBRIDGE_CLI_VERSION} \
            generate-configure --verbose --datadir=/relayer --group=itering

      - uses: int128/diff-action@v1
        with:
          base: lock
          head: _${{ github.base_ref }}_/lock

