name: Check helix relayer config

on:
  pull_request:
#    branches:
#      - main

env:
  HELIXBRIDGE_CLI_VERSION: sha-8c07858

jobs:
  deploy:
    name: Register and generate configure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          path: _source_

      - name: Regiser
        run: |
          docker run -i --rm \
          --name helixbridge \
          -v $PWD:/relayer \
          -e FORCE_COLOR=1 \
          -e SIGNER=${{ secrets.SIGNER }} \
          ghcr.io/helix-bridge/helixbridge-cli:${HELIXBRIDGE_CLI_VERSION} \
            register --verbose --datadir=/relayer --group=itering

      - name: Generate configure
        run: |
          docker run -i --rm \
          --name helixbridge \
          -v $PWD:/relayer \
          -e FORCE_COLOR=1 \
          -e SIGNER=${{ secrets.SIGNER }} \
          ghcr.io/helix-bridge/helixbridge-cli:${HELIXBRIDGE_CLI_VERSION} \
            generate-configure --verbose --datadir=/relayer --group=itering

      - uses: int128/diff-action@v1
        with:
          base: lock
          head: _source_/lock

      - uses: int128/diff-action@v1
        with:
          base: configure
          head: _source_/configure

