name: Check helix relayer config

on:
  pull_request:
#    branches:
#      - main

env:
  HELIXBRIDGE_CLI_VERSION: sha-293ea43

jobs:
  check:
    name: Check changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          ref: main
          path: _source_

      - name: Regiser
        run: |
          docker run -i --rm \
          --name helixbridge \
          -v $PWD:/relayer \
          -e FORCE_COLOR=1 \
          -e SIGNER=${{ secrets.SIGNER }} \
          ghcr.io/helix-bridge/helixbridge-cli:${HELIXBRIDGE_CLI_VERSION} \
            register --verbose --datadir=/relayer --group=itering

      - name: Generate configure
        run: |
          docker run -i --rm \
          --name helixbridge \
          -v $PWD:/relayer \
          -e FORCE_COLOR=1 \
          -e SIGNER=${{ secrets.SIGNER }} \
          ghcr.io/helix-bridge/helixbridge-cli:${HELIXBRIDGE_CLI_VERSION} \
            generate-configure --verbose --datadir=/relayer --group=itering

      - uses: int128/diff-action@v1
        with:
          base: |
            _source_/src
            _source_/lock
            _source_/configure
          head: |
            src
            lock
            configure

